### ISSUE TITLE
Error: [@octokit/webhooks] signature does not match event payload and secret

### ISSUE THREAD

**Issue by 4310V343k** [octokit/app.js#258]
I'm unable to use octokit/app.js because the "breaking" change is only a minor version bump (9.8.0 to 9.8.1) and is "compatible".
https://github.com/octokit/webhooks.js/issues/593

<details>
<summary>Code</summary>

```js
const { App, createNodeMiddleware } = require('@octokit/app');

const app = new App({
    appId: "122298",
    webhooks: { secret: process.env.webhookssecret },
    oauth: {
        clientId: process.env.clientId,
        clientSecret: process.env.clientSecret,
    },
    privateKey: process.env.privateKey,
});

app.webhooks.onError(e => {
    console.error("Webhook failed");
    console.error(e.event);
})

require("http").createServer(createNodeMiddleware(app)).listen(process.env.PORT);
```

</details>

<details>
<summary>Error</summary>

```js
Webhook failed
Error: [@octokit/webhooks] signature does not match event payload and secret
    at verifyAndReceive (C:\Users\denro\sources\ConflictResolver\node_modules\@octokit\app\node_modules\@octokit\webhodules\@octokit\webhooks\dist-node\index.js:259:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async middleware (C:\Users\denro\sources\ConflictResolver\node_modules\@octokit\app\node_modules\@octokit\webhodules\@octokit\webhooks\dist-node\index.js:344:5) {
  event: {
    id: 'b7479b30-d1f8-11eb-94a6-6aa61ee800f9',
    name: 'issue_comment',
    payload: {
      action: 'created',
      issue: [Object],
      comment: [Object],
      repository: [Object],
      sender: [Object],
      installation: [Object]
    },
    signature: 'sha256=6df88c02f8ba3dcc667f1bbcd980ecd4a4ae9f6611efc115df58a8fcffbbacce'
  },
  status: 400
}
```

</details>

**Comment by wolfy1339** [comment]
Let's keep the discussion in the `@octokit/webhooks` repo.

**Comment by gr2m** [comment]
@4310V343k should now be fixed via https://github.com/octokit/webhooks.js/releases/tag/v9.8.3
